"""
philayouter/executor/evaluate_scale.py

Q14 (the experiment queue): size extrapolation 10^3 -> 10^6 -- the
central claim. Trained on community graphs at N=20-50, the equivariant
executor is rolled out on synthetic graphs at N=10^3..10^6 of four families
(grid, random geometric, scale-free, Erdos-Renyi), generated by
generate_corpus.py (sparse, no dense O(N^2) anywhere -- the machine OOM'd on
such tests on 2026-08-13, see EXPERIMENT_QUEUE.md).

Design (recorded 2026-08-14):
- Ground truth at 10^5-10^6 is NOT a recorded FR trajectory -- FR's own
  update is O(N^2) (160 GB at N=10^6), which is both infeasible here and a
  real gap in the field (force-directed layout at that scale uses Barnes-Hut
  approximations). So the size-extrapolation metric is intrinsic layout
  quality + stability, the same way §7's quality axis is scored: FR residual
  force (residual_fr_force in eval/metrics.py), stress, and convergence of
  the rollout. This is the honest, reproducible version of the claim.
- Per-step pipeline is sparse-safe: kd kNN (scipy cKDTree) + model forward,
  both O(N log N) / O(N*k). Structural encoding is LapPE-only
  (use_rrwp=False, fast_eigsh) per the resolved Q13/Q14 decision.
- Temperature: k-normalized (SCALE_NORMALIZATION.md), t0 from the grid init.

Usage:
    .venv/bin/python -m philayouter.executor.evaluate_scale \
        --checkpoint checkpoints/phi1_v1/executor_best.pt \
        --corpora data/corpora --sizes 1000 10000 100000 \
        --device cuda:0 --T 50
"""

import argparse
import os
import time

import numpy as np
import torch

from .generate_corpus import FAMILIES
from .geometric import build_knn_graph
from .model import EquivariantExecutor
from .structural import StructuralEncoder


def k_unit_init(n: int, device):
    """Grid init with N-invariant k-unit span (SCALE_NORMALIZATION.md §4, opt b).

    Training (N=20-50): raw canvas [-1,1]^2, k=1/sqrt(N), so |pos/k| spans
    ~sqrt(50)~7 in k units. To keep that range N-invariant (measured failure
    2026-08-14: |pos_k| scaling with sqrt(N) made N=1000 see pos~31 vs train 7
    and the rollout diverged exponentially by step 7), the raw canvas must
    GROW with N so the k-unit span stays ~constant. Returns k-unit positions
    with the same |pos|~7 span as training regardless of N."""
    grid_size = int(np.ceil(np.sqrt(n)))
    rows = int(np.ceil(n / grid_size))
    pos = np.zeros((n, 2), dtype=np.float64)
    for i in range(n):
        u = (i % grid_size) / max(grid_size - 1, 1)
        v = (i // grid_size) / max(rows - 1, 1)
        pos[i, 0] = 2 * u - 1
        pos[i, 1] = 2 * v - 1
    # raw canvas is [-1,1] (span ~2). Training k-unit span |pos/k| ~
    # (raw_span/2) * sqrt(N_train) ~ sqrt(50) ~ 7. Keep |pos_k| ~ 7 constant:
    # pos_k = (raw_pos) * 7  -> spans [-7, 7], matching the training range
    # exactly at every N (this is option (b): canvas grows so k-unit density
    # is N-invariant).
    pos_k = pos * 7.0  # raw spans [-1,1] -> [-7, 7], |pos_k| ~ 7 == training
    return torch.from_numpy(pos_k.astype(np.float32)).to(device)
def sparse_quality(final: np.ndarray, edge_index: np.ndarray, k: float):
    """Intrinsic layout-quality metrics that stay sparse at N=10^6 (no O(N^2)
    matrix anywhere -- the machine OOM'd on such tests 2026-08-13):

      radius      : max |x| over the final layout, in k units -- a degenerate
                    collapse would shrink this; unbounded growth would blow it.
      edge_stretch: mean ratio of embedded edge length to k (ideal edge length).
                    ~O(1) means edges sit near their target length.
      mean_degree_span: sanity (kept small).
    Returns (radius, edge_stretch)."""
    r = float(np.abs(final).max())
    row, col = edge_index[0], edge_index[1]
    e_len = np.linalg.norm(final[row] - final[col], axis=1)
    stretch = float(e_len.mean() / k)
    return r, stretch


@torch.no_grad()
def rollout_scale(encoder, model, edge_index, n, device, T=50, skip_encoding=False):
    """Roll the model out on a corpus graph. Returns final raw-frame positions
    [N,2] (k-normalized internally) and per-step mean displacement."""
    k = float(np.sqrt(1.0 / n))
    pos = k_unit_init(n, device)  # already k-unit, N-invariant span
    edge_index = edge_index.to(device)
    # temperature in k units, matched to training (t0/k ~ 1.0-1.4 at N=20-50):
    # use the N-invariant convention tau_tilde = t0_tilde, with t0_tilde ~ 1.2.
    temps = np.maximum(1.2 - np.arange(T) * (1.2 / (T + 1)), 1e-6).astype(np.float32)

    if skip_encoding:
        node_feat = torch.randn(n, model.node_encoder.in_features, device=device)
    else:
        node_feat = encoder.forward(edge_index.cpu(), n).to(device)
    step_mags = []
    diverged_at = -1
    for t in range(T):
        tau_val = float(temps[t])  # already k-normalized
        tau = torch.full((n, 1), tau_val, device=device)
        dX = model(node_feat, edge_index, pos, tau)
        pos = pos + dX
        step_mags.append(dX.norm(dim=-1).mean().item())
        if not torch.isfinite(pos).all():
            diverged_at = t
            break
    if diverged_at >= 0:
        return None, np.array(step_mags), diverged_at
    return (pos * k).cpu().numpy(), np.array(step_mags), -1


def main():
    parser = argparse.ArgumentParser(description="Q14: size extrapolation 10^3-10^6")
    parser.add_argument("--checkpoint", required=True)
    parser.add_argument("--corpora", default="data/corpora")
    parser.add_argument("--sizes", type=int, nargs="+", default=[1000, 10000, 100000, 1000000])
    parser.add_argument("--families", nargs="+", default=list(FAMILIES.keys()))
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--T", type=int, default=50)
    parser.add_argument("--hidden_dim", type=int, default=64)
    parser.add_argument("--lap_k", type=int, default=10)
    parser.add_argument("--rw_k", type=int, default=16)
    parser.add_argument("--chunk", type=int, default=None,
                        help="per-edge chunk size for the model's message "
                             "passing + readout (EquivariantExecutor(chunk=...)). "
                             "Bounded memory to O(chunk) edge messages, which is "
                             "what makes N=10^6 run without the 24 GB OOM "
                             "(Q22/Q14 memory wall). None = monolithic, "
                             "bit-identical to pre-chunk checkpoints.")
    parser.add_argument("--skip_encoding", action="store_true",
                        help="random node_feat instead of LapPE. The Q14 finding: "
                             "eigsh on the N=10^6 grid's degenerate spectrum is "
                             "minutes-to-tens-of-minutes (a CPU wall, not GPU), "
                             "so per-step pipeline timing at 10^6 uses random "
                             "features and reports encoding as skipped, exactly "
                             "as benchmark_wallclock does.")
    args = parser.parse_args()

    if args.device.startswith("cuda") and not torch.cuda.is_available():
        args.device = "cpu"
    device = torch.device(args.device)

    ckpt = torch.load(args.checkpoint, map_location=device, weights_only=False)
    cargs = ckpt["args"]
    # encoder runs the eigendecomposition + SignNet, both CPU-bound (scipy
    # eigsh is CPU-only); keep it on CPU and move only its output to device.
    encoder = StructuralEncoder(
        out_dim=cargs.get("hidden_dim", args.hidden_dim),
        lap_k=cargs.get("lap_k", args.lap_k),
        rw_k=cargs.get("rw_k", args.rw_k),
        fast_eigsh=True,
        use_rrwp=False,
    )  # CPU
    num_teachers = len(ckpt["teachers"]) if isinstance(ckpt.get("teachers"), dict) else 1
    model = EquivariantExecutor(
        node_feat_dim=cargs.get("hidden_dim", args.hidden_dim),
        hidden_dim=cargs.get("hidden_dim", args.hidden_dim),
        k_geo=cargs.get("k_geo", 10),
        num_teachers=num_teachers,
        knn_backend="kd",
        chunk=args.chunk,
    ).to(device)
    encoder.load_state_dict(ckpt["encoder_state_dict"])
    model.load_state_dict(ckpt["model_state_dict"])
    encoder.eval()
    model.eval()
    print(f"loaded checkpoint (epoch {ckpt.get('epoch')}, val {ckpt.get('val_loss'):.6f})")

    print(f"\n{'family':>10} {'N':>9} | {'radius/k':>9} {'edge stretch':>12} {'late step-mag':>12} {'wall-clock':>9}")
    print("-" * 70)
    for fam in args.families:
        for n in args.sizes:
            path = os.path.join(args.corpora, f"{fam}_{n}.pt")
            if not os.path.isfile(path):
                print(f"{fam:>10} {n:>9,} | (corpus file missing)")
                continue
            ei = torch.load(path)
            t0 = time.time()
            final, step_mags, div_at = rollout_scale(encoder, model, ei, n, device,
                                                     T=args.T, skip_encoding=args.skip_encoding)
            dt = time.time() - t0
            if final is None:
                print(f"{fam:>10} {n:>9,} | DIVERGED at step {div_at}            {dt:>8.1f}s", flush=True)
                continue
            r, stretch = sparse_quality(final, ei.numpy(), float(np.sqrt(1.0 / n)))
            late = float(step_mags[-5:].mean())
            print(f"{fam:>10} {n:>9,} | {r:>9.2f} {stretch:>12.3f} {late:>12.2e} {dt:>8.1f}s", flush=True)


if __name__ == "__main__":
    main()
